=== paperhive/paperhive-api/schemas/publication_post.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://paperhub.io/api/v0/schemas/publication_post.json",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema_id": {
      "id": "http://json-schema.org/draft-04/schema#",
      "type": "string",
      "additionalProperties": false
    },
    "origins": {
      "id": "http://jsonschema.net/origins#",
      "type": "array",
      "additionalProperties": false,
      "items": {
        "id": "http://jsonschema.net/origins/0#",
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "url": {
            "id": "http://jsonschema.net/origins/0/url#",
            "type": "string"
          },
          "pdf": {
            "id": "http://jsonschema.net/origins/0/pdf#",
            "type": "string"
          },
          "id": {
            "id": "http://jsonschema.net/origins/0/id#",
            "type": "string"
          },
          "type": {
            "id": "http://jsonschema.net/origins/0/type#",
            "type": "string"
          },
          "date_added": {
            "id": "http://jsonschema.net/origins/0/date_added#",
            "type": "string"
          },
          "added_by": {
            "id": "http://jsonschema.net/origins/0/added_by#",
            "type": "string"
          }
        },
        "required": [
          "url",
          "type",
          "date_added",
          "added_by"
        ]
      }
    },
    "md5sum": {
      "id": "http://jsonschema.net/md5sum#",
      "type": "string"
    },
    "authors": {
      "id": "http://jsonschema.net/authors#",
      "type": "array",
      "items": {
        "$ref": "author.json"
      }
    },
    "title": {
      "id": "http://jsonschema.net/title#",
      "type": "string"
    },
    "date": {
      "id": "http://jsonschema.net/date#",
      "type": "string"
    },
    "journal": {
      "id": "http://jsonschema.net/journal#",
      "type": "string"
    },
    "volume": {
      "id": "http://jsonschema.net/volume#",
      "type": "string"
    },
    "number": {
      "id": "http://jsonschema.net/number#",
      "type": "string"
    }
  },
  "required": [
    "origins",
    "md5sum",
    "authors",
    "title",
    "date"
  ]
}

=== paperhive/paperhive-api/examples/publication_post.json
{
  "$schema": "http://paperhub.io/api/v0/schemas/publication_post.json",
  "origins": [
    {
      "url": "http://arxiv.org/abs/1208.0264",
      "pdf": "http://arxiv.org/pdf/1208.0264v3",
      "id": "arXiv:1208.0264",
      "type": "arxiv",
      "date_added": "2014-10-15T16:31:32.040Z",
      "added_by": "andrenarchy"
    }
  ],
  "md5sum": "e0a8bc29aff95372c49844f305973994",
  "authors": ["andrenarchy id", "nschloe id"],
  "title": "Preconditioned Recycling Krylov subspace methods for self-adjoint problems",
  "date": "2014-06-12T13:55:10.000Z",
  "journal": "arxiv id"
}
